name: Cypress Tests
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        shard: ["1/3", "2/3", "3/3"]
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests

      - name: Yarn install
        run: yarn install --frozen-lockfile

      - name: Cypress run
#        run: yarn run cypress:run:headed
        run: |
          yarn nx run-many \
            --target=mq-e2es \
            --projects=app-e2e \
            --parallel=false \
            --output-style=stream \
            --shard=${{ matrix.shard }}
        env:
          # Needed for the E2E tests DDog CI Visibility
          # For E2Es the matrix.projects will always be a single project
          DD_CIVISIBILITY_AGENTLESS_ENABLED: true
          DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DD_ENV: maxi-ci
          DD_SERVICE: maxi-cypress
        #          DD_TRACE_DEBUG: 1
